# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - 'size' refers to the length of the shared border between solid black and solid white rectangle.
#   See README.md or https://github.com/AprilRobotics/apriltag/wiki/AprilTag-User-Guide#pose-estimation for details.
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
    {id: 0, size: 0.055},
    {id: 1, size: 0.055},
    {id: 2, size: 0.055},
    {id: 3, size: 0.055},
    {id: 4, size: 0.055},
    {id: 5, size: 0.055},
    {id: 6, size: 0.055},
    {id: 7, size: 0.055},
    {id: 8, size: 0.055},
    {id: 9, size: 0.055},
    {id: 10, size: 0.055},
    {id: 11, size: 0.055},
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]

tag_bundles:
  [
    {
      name: 'my_bundle',
      layout:
        [
          {id: 0, size: 0.06, x: 0.0000, y: 0.0000, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
          {id: 11, size: 0.06, x: 0.1369, y: -0.2103, z: -0.0024, qw: 0.9997, qx: -0.0181, qy: 0.0135, qz: 0.0010},
          {id: 6, size: 0.06, x: 0.0008, y: -0.1391, z: 0.0031, qw: 0.9997, qx: -0.0167, qy: -0.0149, qz: 0.0035},
          {id: 2, size: 0.06, x: 0.1356, y: 0.0004, z: -0.0012, qw: 0.9999, qx: -0.0043, qy: 0.0129, qz: 0.0024},
          {id: 5, size: 0.06, x: 0.1354, y: -0.0693, z: 0.0011, qw: 0.9997, qx: -0.0014, qy: 0.0251, qz: 0.0048},
          {id: 4, size: 0.06, x: 0.0683, y: -0.0696, z: 0.0017, qw: 1.0000, qx: 0.0027, qy: 0.0019, qz: 0.0018},
          {id: 3, size: 0.06, x: 0.0008, y: -0.0697, z: 0.0024, qw: 0.9999, qx: -0.0030, qy: -0.0097, qz: -0.0007},
          {id: 1, size: 0.06, x: 0.0679, y: -0.0003, z: 0.0006, qw: 1.0000, qx: -0.0070, qy: 0.0042, qz: 0.0018},
          {id: 7, size: 0.06, x: 0.0682, y: -0.1389, z: 0.0022, qw: 0.9996, qx: -0.0255, qy: 0.0089, qz: 0.0027},
          {id: 8, size: 0.06, x: 0.1357, y: -0.1388, z: 0.0013, qw: 0.9996, qx: -0.0179, qy: 0.0228, qz: 0.0016},
          {id: 10, size: 0.06, x: 0.0685, y: -0.2086, z: 0.0030, qw: 0.9999, qx: -0.0099, qy: 0.0124, qz: 0.0025},
          {id: 9, size: 0.06, x: 0.0001, y: -0.2095, z: 0.0016, qw: 0.9997, qx: -0.0220, qy: 0.0039, qz: 0.0063}
        ]
    }
  ]
